# Generated by Django 5.0.2 on 2024-02-26 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("staffs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="staffs",
            name="admin",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="notificationstaffs",
            name="stafff_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="staffs.staffs"
            ),
        ),
        migrations.AddField(
            model_name="leavereportstaff",
            name="staff_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="staffs.staffs"
            ),
        ),
        migrations.AddField(
            model_name="feedbackstaffs",
            name="staff_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="staffs.staffs"
            ),
        ),
    ]
